#!/bin/bash
# Laura Dean
# 19/8/25
# script written for running on the UoN HPC Ada

# script to align the predicted protein sequence from our hagfish assembly
# with the sequence generated by Chris from the short read data to compare them


# align the sequences by pasting the fasta into https://www.genome.jp/tools-bin/clustalw
# on inspecting the alignment, sequences are the same apart from the absence of the first
# intron. I'm going to try re-running with a prediction sequence that contains the first
# intron. 


